---
title: "Concrete Compressive Strength"
subtitle: "CTC-34_Lab2: Evolução Grmátical"
author: "Matheus Vidal & Pedro Alves"
date: "17/11/2019"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Definição da Gramática

```{r}
# Limpa área de trabalho
rm(list = ls())

# Não Terminais
V <- c("<exp>","<op>","<var>")

# Terminais
#sigma <- c("+","-","/","*","x","y","z","u","v","w")
sigma <- c("+","-","/","*","x","y")

# Símbolo Inicial
S <- "<exp>"

# Produções
P <- list(c("<exp><op><exp>","<var>"),c("+","-","/","*"),c("x","y"))

```

## Definindo os Cromossomos
```{r}
cromo_size <- 6
cromo_quant <- 4
max_gene <- 100
C <- matrix(sample(max_gene,cromo_size),cromo_quant,cromo_size) # Ci = C[i,]

```

## Carregamento dos Dados de Treinamento

```{r}
trainingData <- read.csv(file="training.csv", header=TRUE, sep=",")

```

## Gerando Derivação

```{r}
# SOMENTE PARA TESTE
C[1,] <- c(4,15,75,8,41,12)
C[2,] <- c(6,10,255,7,50,35)
C[3,] <- c(9,40,7,43,2,11)
C[4,] <- c(20,5,200,5,67,23)
# FIM
derivacao <- rep(S,cromo_quant) # símbolo inicial
for (i in 1:cromo_quant) {
  S <- "<exp>"
  j <- 0
  while (S!="<NA>"){
    j <- j%%cromo_size + 1
    if (S=="<exp>"){
      rule <- P[[1]][1+C[i,j]%%length(P[[1]])] # determina a regra a ser aplicada
      derivacao[i] <- sub(S, rule, derivacao[i]) # atualiza derivacao por substituição
      S <- str_match(derivacao[i], "<(.*?)>") # acha o primeiro <..>
      S <- paste("<",S[,2],">",sep = "") # novo símbolo
    } else if (S=="<op>"){
      rule <- P[[2]][1+C[i,j]%%length(P[[2]])] # determina a regra a ser aplicada
      derivacao[i] <- sub(S, rule, derivacao[i]) # atualiza derivacao por substituição
      S <- str_match(derivacao[i], "<(.*?)>") # acha o primeiro <..>
      S <- paste("<",S[,2],">",sep = "") # novo símbolo
    } else if (S=="<var>"){
      rule <- P[[3]][1+C[i,j]%%length(P[[3]])] # determina a regra a ser aplicada
      derivacao[i] <- sub(S, rule, derivacao[i]) # atualiza derivacao por substituição
      S <- str_match(derivacao[i], "<(.*?)>") # acha o primeiro <..>
      S <- paste("<",S[,2],">",sep = "") # novo símbolo
    }
  }
}
```

## ATENÇÂO! SOMENTE PARA TESTE!

```{r}
testData <- rbind(c(0.9,0.8,1.61),c(0.3,0.1,0.19),c(0.5,0.2,0.45),c(0.88,0.5,1.2744),c(0.6,0.7,1.06))

```

## Avaliação dos Cromossomos

```{r}
#training.model <- trainingData[,c("strength")]
training.model <- testData[,c("strength")]
erroQuadraticoMedio <- rep(0,cromo_quant)
for (k in 1:cromo_quant){
  training.data <- c()
  for (i in 1:length(training.model)){
    x <- testData[i,1]
    y <- testData[i,2]
    training.data <- c(training.data,eval(parse(text=derivacao[k])))
  }
  erroQuadraticoMedio[k] <- mean((training.data - (training.model))^2) 
}
```

## Torneio de Cromossomos
```{r}
sorteados <- c()
for (i in 1:cromo_quant){
  sorteio <- sample(cromo_quant,2)
  sorteados <- c(sorteados,which.max(erroQuadraticoMedio))
}

```


